### ISSUE TITLE
Legacy P12 conversion 

### ISSUE THREAD

**Issue by Proph151Music** [StardustCollective/nodectl#7]
In the new openssl it causes incompatibilities with some p12 files that were created using the older openssl versions.  nodectl can add support for older p12 files simply by introducing the -legacy switch into the code where it unlocks older p12 files.

The newer openssl does use a better encryption though... So I would recommend a command that users of nodectl can use to convert a legacy P12 into the newer encryption without losing the current nodeID.

Maybe a new parameter that replaces the current p12 file with an upgraded p12 file that the user should be advised to backup.

```sudo nodectl -p12upgrade```

**Comment by netmet1** [comment]
added for `v2.9.0` - closing.
